### ISSUE TITLE
 please provide a simplified version

### ISSUE THREAD

**Issue by danpanwan** [snu-adsl/DEEP-BO#2]
i have read your code for 2 days,and i have not run it successfully. it is too too large and complicated. could you please provide a simplified version just using your strategy for HPO of 
 DNN without comparing with other stategies?  many thanks.

**Comment by hyunghunny** [comment]
Firstly, thank you for your interest and also feel sorry to hear that you could not build it successfully.

Could you please to provide some more information about failures or sufferings that you've experienced?
Without it, I could not figure out your points regarding **simplified version**. 

Also, note that some help materials are described in this [Wiki](https://github.com/snu-adsl/DEEP-BO/wiki) 
This [runner interface](https://github.com/snu-adsl/DEEP-BO/wiki/3.2.-Runner-Interface) may be helpful to you.

Sincerely,

**Comment by hyunghunny** [comment]
Closed this issue due to no more reply.
