### ISSUE TITLE
hpo_runner undefined variables

### ISSUE THREAD

**Issue by hrakhshani** [snu-adsl/DEEP-BO#3]
In hpo_runner.py, val_args variable is undefined and I think we have to change it to run_args. However, I still got an error :(

Launch train_node.py to be served as train node...
Progress can be monitored via train_cpu0.log
Evaluation will be performed via tune_kin8nm_mlp...
 * Serving Flask app "WebServiceManager" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:6100/ (Press CTRL+C to quit)
 * Restarting with stat
Progress can be monitored via train_cpu0.log
Evaluation will be performed via tune_kin8nm_mlp...
 * Debugger is active!
 * Debugger PIN: 327-110-034
Progress can be monitored via tune_kin8nm_mlp.log
This will be ended near Sat May  9 05:54:12 2020
127.0.0.1 - - [09/May/2020 02:54:16] "GET / HTTP/1.1" 200 -
**Invalid train node setting: handshaking failed.**
HPO has been finished. Press control+C to terminate

**Comment by hyunghunny** [comment]
Thank you for announcing my mistake in this issue.
I've fixed them as https://github.com/snu-adsl/DEEP-BO/commit/dec7471d4b26d72fbdce1a0990c6da826bc577b6

Please pull this update to your code and try it again.
Sincerely

**Comment by hyunghunny** [comment]
Handskaing issue resolved. The below excerpted from e-mail reply from @ML-MHs 
Thank you very much!


````

I found the problem and it was related to json.loads function inside remote_job.py. I have to pass 
everything as utf-8 format and note byte. 

````
