### ISSUE TITLE
How do I run this project locally？

### ISSUE THREAD

**Issue by XueAdas** [snu-adsl/DEEP-BO#4]
This is a great project! 
I encountered errors when I was running locally with hpo_runner.py,  so how do I run this project locally？

Specific error messages:
"Invalid train node setting: handshaking failed."

**Comment by XueAdas** [comment]
I got it

**Comment by hyunghunny** [comment]
Dear @XueAdas 
Thank you for your interest and appreciation.

I'm sorry that I could not notify your issue 2 weeks ago.
However, I'm glad you had been fixed it yourself without any support.

Sincerely, 
HH
